import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./ui/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-svh text-center text-[#c38b8b] bg-gradient-to-r from-black from-10% to-[#9b5d73]`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
